[theme]
primaryColor = "#4361ee"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[global]
showWarningOnDirectExecution = true
disableWidgetStateDuplication = true 